# main text of home
name: Yasel Garces
bio: Strategic & Creative Data Scientist💡 Highly skilled in Machine Learning, Statistic, and Programming ♣ Helping Companies Succeed 🚀 📈.
external-image: true
picture: image/Yasel_Image.jpg

# If you want to include your resume, set to true
# and specify source (external or local).
resume: true
resume-external: true
resume-url: resume/Resume Yasel Garces.pdf
url: https://yasel-garces.github.io/Portafolio---Yasel-Garces/

permalink: /:title/

linkedin: yasel-garces-suarez
github: Yasel-Garces
email: 88yasel@gmail.com
authors:
    name: Yasel Garces
    external-image: false
    picture: image/Yasel_Image.jpg
    #twitter:
 

# do you want a larger site? change the option below
#normal = 560px / large = 810px
width: normal

# if you don't need projects, comment the *projects* configs below
projects: true

# if you don't need "about" or "blog", comment them out below
about: true
#blog: false

# show author block at the end of a post ?
show-author: true

plugins:
  - jekyll-seo-tag
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-admin
  - jekyll-paginate-v2

jekyll-mentions:
  base_url: https://github.com

compress_html:
  ignore:
    envs:
      - development
      - stage

exclude:
  [
    "travis.sh",
    "README.md",
    "Gemfile",
    "Gemfile.lock",
    "FAQ.md",
    "node_modules",
    "vendor",
  ]
